services:
  - type: web
    name: mern1-frontend
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: NODE_VERSION
        value: 22.16.0

  - type: web
    name: mern1-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: PORT
        value: 5000

